#######################################
##########  Padavan_4.4 KVR  ##########

name: K2P-USB_测试
# Controls when the action will run. 
on: 
  #push:
  workflow_dispatch:
  
env:
  src_git: https://github.com/litter6210/padavan-4.4.git
  src_dir: /opt/padavan
  work_dir: /opt/padavan/trunk
  firmware_dir: /opt/firmware
  config_file: K2P-USB.config
  custom_script: custom.sh

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        device: [K2P-USB]
    permissions: 
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      if: (!cancelled())
      run: |
        sudo apt-get -qq install -y \
          unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
          fakeroot kmod cpio git python3-docutils gettext automake autopoint \
          texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin &
          wait
          sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source and Download toolchain
      if: (!cancelled())
      run: |
        git clone --depth=1 $src_git $src_dir
        cd $src_dir/toolchain-mipsel && chmod +x dl_toolchain.sh
        ./dl_toolchain.sh
    
    - name: Import Custom configs
      if: (!cancelled())
      run: |
        #cp $config_file $work_dir/configs/templates/${{ matrix.device }}.config
        #mv $config_file $work_dir/.config
        #mv $custom_script $work_dir/
        #cd $work_dir
        #chmod +x build_firmware_modify && chmod +x $custom_script
        #./$custom_script

        ########################################################################################
        ############  修改默认参数  #############################################################
        
        ##  修改主界面的版本号为编译时间
        sed -i 's/FIRMWARE_BUILDS_REV=*/FIRMWARE_BUILDS_REV=$(shell date +%Y%m%d/g 2>/dev/null)' /opt/rt-n56u/trunk/versions.inc

        ##  修改WIFI的地区，源码中默认2.4G是中国区，5G是美国区，统一改成中国区
        sed -i 's/"US"/"CN"/g' /opt/rt-n56u/trunk/user/shared/defaults.h

        ##  修改NTP时钟同步服务器；
        sed -i 's/"ntp1.aliyun.com"/"pool.ntp.org"/g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/"2001:470:0:50::2"/"time.pool.aliyun.com"/g' /opt/rt-n56u/trunk/user/shared/defaults.h

        ##  修改界面中的字符，将2.4G改成2.4GHz、5G改成5GHz，更加严谨
        sed -i 's/2.4G/2.4GHz/g' /opt/rt-n56u/trunk/user/www/dict/CN.dict
        sed -i 's/5G/5GHz/g' /opt/rt-n56u/trunk/user/www/dict/CN.dict
        sed -i 's/2.4G/2.4GHz/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/state.js
        sed -i 's/value="5G"/value="5GHz"/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/state.js

        ##  在编译XXXX的固件之前，修改LAN口IP地址
        sed -i 's/"192.168.2.1"/"192.168.123.1"/g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/"192.168.2.100"/"192.168.123.100"/g' /opt/rt-n56u/trunk/user/shared/defaults.h
        sed -i 's/"192.168.2.244"/"192.168.123.244"/g' /opt/rt-n56u/trunk/user/shared/defaults.h

        sed -i 's/192.168.2.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/dict/CN.dict
        sed -i 's/192.168.2.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/dict/EN.footer

        sed -i 's/192.168.2.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/Restarting.asp
        sed -i 's/192.168.1.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/Advanced_APLAN_Content.asp
        sed -i 's/192.168.1.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/Advanced_LAN_Content.asp
        sed -i 's/192.168.1.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/general.js
        sed -i 's/192.168.1.1/192.168.2.1/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/Advanced_SettingBackup_Content.asp

        ##  设置编译固件默认为 AP模式
        #echo "#define BOARD_ROLE_REPEATER	1" >> /opt/rt-n56u/trunk/configs/boards/${{ matrix.device }}/board.h

        ##  修改源码升级参数
        sed -i 's/"<a target='_blank' href='https://services13.ieee.org/RST/standards-ra-web/rest/assignments/?registry=MAC&text=" + client[2].substr(0,6) + "'>" + mac_add_delimiters(client[2]) + "</a>"/mac_add_delimiters(client[2])/g' /opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/device-map/clients.asp
        

        ########################################################################################
        ############  清除默认选项  #############################################################
        sed -i 's/=y/=n/g' /opt/rt-n56u/trunk/configs/templates/${{ matrix.device }}.config


        ########################################################################################
        ############  定义插件选项  #############################################################
        sed -i 's/CONFIG_FIRMWARE_ENABLE_IPV6=n/CONFIG_FIRMWARE_ENABLE_IPV6=y/g' /opt/rt-n56u/trunk/configs/templates/${{ matrix.device }}.config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_LANG_CN=n/CONFIG_FIRMWARE_INCLUDE_LANG_CN=y/g' /opt/rt-n56u/trunk/configs/templates/${{ matrix.device }}.config
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=y" >>/opt/rt-n56u/trunk/configs/templates/${{ matrix.device }}.config


    - name: Build the firmware
      if: (!cancelled())
      id: compile
      run: |
        cd $work_dir
        fakeroot ./build_firmware_modify ${{ matrix.device }} 0
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        mkdir -p $firmware_dir
        mv images/*.trx $firmware_dir

    - name: Upload firmware directory
      uses: actions/upload-artifact@v4
      if: ${{ success() }} && !cancelled()
      with:
        name: ${{ matrix.device }}
        path: ${{ env.firmware_dir }}
        if-no-files-found: error
        

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
       GITHUB_TOKEN: ${{ github.token }}
      with:
       files: |
         ${{ env.firmware_dir }}/*.trx
       tag_name: ${{ steps.compile.outputs.release_tag }}
